src/apps/bible/urls.py
from django.conf.urls import url

from src.apps.bible import views

urlpatterns = [
    url(r'^indeks/', views.IndexView.as_view(), name='index'),
    url(r'^(?P<slug>.*)', views.ShowView.as_view(), name='show'),
]

src/apps/parametrizedimage/urls.py
from django.conf.urls import url

from src.apps.parametrizedimage import views

urlpatterns = [
    url(r'^indeks/', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>.*)', views.ShowView.as_view(), name='show'),
]

src/apps/staticpages/urls.py
from django.conf.urls import url

from src.apps.staticpages import views

urlpatterns = [
    url(r'^kontakt/', views.ContactView.as_view(), name='contact'),
]

src/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views import defaults as views_defaults

from src.apps.home.views import HomepageView


urlpatterns = [
    url(r'^$', HomepageView.as_view(), name='homepage'),
    url(r'^', include('src.apps.staticpages.urls', namespace='staticpages')),
    url(r'^biblie/', include('src.apps.bible.urls', namespace='bible')),
    url(r'^karty/', include('src.apps.parametrizedimage.urls', namespace='parametrizedimage')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # For viewing 404 and 500 pages in debug mode
    urlpatterns += [
        url(r'^404/$', views_defaults.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', views_defaults.server_error),
    ]

    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/apps/bible/models.py
from django.db import models


class Bible(models.Model):
    title = models.TextField()
    slug = models.TextField()
    cover = models.ImageField()
    pdf_file = models.FileField()


class BiblePage(models.Model):
    bible = models.ForeignKey(Bible)
    ordering = models.IntegerField()
    image_small = models.ImageField()
    image_large = models.ImageField(null=True, blank=True)

src/apps/parametrizedimage/models.py
from django.db import models


CARD_PARAMETERS = [
    {
        'csv_field_name': 'miejsce badania',
        'parameter_name': 'parameter_miejsce_badania',
        'parameter_name_human': 'Miejsce badania',
        'type': 'string',
        'more_important': True,
    },
    {
        'csv_field_name': 'data badania',
        'parameter_name': 'parameter_data_badania',
        'parameter_name_human': 'Data badania',
        'type': 'string',
        'more_important': True,
    },
    {
        'csv_field_name': 'rocznik',
        'parameter_name': 'parameter_rocznik',
        'parameter_name_human': 'Rocznik',
        'type': 'float',
        'round': True,
        'more_important': True,
    },
    {
        'csv_field_name': 'wyznanie',
        'parameter_name': 'parameter_wyznanie',
        'parameter_name_human': 'Wyznanie',
        'type': 'string',
        'more_important': True,
    },
    {
        'csv_field_name': 'jezyk',
        'parameter_name': 'parameter_jezyk',
        'parameter_name_human': 'Język',
        'type': 'string',
        'more_important': True,
    },
    {
        'csv_field_name': 'powiat urodzenia',
        'parameter_name': 'parameter_powiat_urodzenia',
        'parameter_name_human': 'Powiat urodzenia',
        'type': 'string',
        'more_important': True,
    },
    {
        'csv_field_name': 'waga',
        'parameter_name': 'parameter_waga',
        'parameter_name_human': 'Waga',
        'type': 'float',
        'more_important': True,
    },
    {
        'csv_field_name': 'wzrost',
        'parameter_name': 'parameter_wzrost',
        'parameter_name_human': 'Wzrost',
        'type': 'float',
        'more_important': True,
    },
    {
        'csv_field_name': 'gnathion',
        'parameter_name': 'parameter_wzrost_od_ziemi_do_podbrodka',
        'parameter_name_human': 'Wzrost od ziemi do podbródka',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'suprasternale',
        'parameter_name': 'parameter_wzrost_od_ziemi_do_mostka',
        'parameter_name_human': 'Wzrost od ziemi do mostka',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'symphysion',
        'parameter_name': 'parameter_wzrost_do_wzgorka_lonowego',
        'parameter_name_human': 'Wzrost od ziemi do wzgórka łonowego',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'tibiale',
        'parameter_name': 'parameter_wzrost_do_kolan',
        'parameter_name_human': 'Wzrost do kolan',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'sphyrion',
        'parameter_name': 'parameter_wzrost_do_kostki',
        'parameter_name_human': 'Wzrost do kostki',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'akromion',
        'parameter_name': 'parameter_wzrost_od_ziemi_do_ramienia',
        'parameter_name_human': 'Wzrost od ziemi do ramienia',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'radiale',
        'parameter_name': 'parameter_od_ziemi_do_lokcia',
        'parameter_name_human': 'Wzrost od ziemi do łokcia',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'stylion',
        'parameter_name': 'parameter_od_ziemi_do_nadgarstka',
        'parameter_name_human': 'Wzrost od ziemi do nadgarstka',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'daktylion',
        'parameter_name': 'parameter_od_ziemi_do_konca_palca_srodkowego',
        'parameter_name_human': 'Wzrost od ziemi do końca palca środkowego',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'pterion-akrop(odion).',
        'parameter_name': 'parameter_dlugosc_stopy_od_piety_do_duzego_palca_u_nogi',
        'parameter_name_human': 'Długość stopy od pięty do dużego palca u nogi',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Mtr. I,-mtr. m.',
        'parameter_name': 'parameter_szerokosc_stopy',
        'parameter_name_human': 'Szerokość stopy',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Akrom-Akrom',
        'parameter_name': 'parameter_szerokosc_w_barkach',
        'parameter_name_human': 'Szerokość w barkach',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Śr. piers. poprz.',
        'parameter_name': 'parameter_szerokosc_klatki_piersiowej',
        'parameter_name_human': 'Szerokość klatki piersiowej',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Śr. piers. strz.',
        'parameter_name': 'parameter_glebokosc_klatki_piersiowej',
        'parameter_name_human': 'Głębokość klatki piersiowej',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Iliocrist.-illiocr.',
        'parameter_name': 'parameter_szerokosc_w_biodrach',
        'parameter_name_human': 'Szerokość w biodrach',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Metacar. l.-met. m.',
        'parameter_name': 'parameter_szerokosc_dloni',
        'parameter_name_human': 'Szerokość dłoni',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Phal(angion)III-Dakt.',
        'parameter_name': 'parametr_dlugosc_palca_srodkowego',
        'parameter_name_human': 'Długość palca środkowego',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Nasion.-Gnath.',
        'parameter_name': 'parametr_wysokosc_twarzy_od_brody_do_poziomu_oczu',
        'parameter_name_human': 'Wysokość twarzy od brody do poziomu oczu',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Nas.-Prosth.',
        'parameter_name': 'parameter_od_oczu_do_gornej_szczeki',
        'parameter_name_human': 'Odległość od oczu do górnej szczęki',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Nas.-Subnas.',
        'parameter_name': 'parameter_wysokosc_nosa',
        'parameter_name_human': 'Wysokość nosa',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Alare.-Alare.',
        'parameter_name': 'parameter_szerokosc_nosa_u_podstawy',
        'parameter_name_human': 'Szerokość nosa u podstawy',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Glab.-Opist.',
        'parameter_name': 'parameter_dlugosc_czaszki_od_czola_do_potylicy',
        'parameter_name_human': 'Długość czaszki od czoła do potylicy',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Eur.-Eur.',
        'parameter_name': 'parameter_szerokosc_czaszki_na_wysokosci_oczu',
        'parameter_name_human': 'Szerokość czaszki na wysokości oczu',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Mast.-Mast.',
        'parameter_name': 'parameter_szerokosc_czaszki_na_wysokosci_uszu',
        'parameter_name_human': 'Szerokość czaszki na wysokości uszu',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Front.-Front.',
        'parameter_name': 'szerokosc_czola',
        'parameter_name_human': 'Szerokość czoła',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Zyg.-Zyg.',
        'parameter_name': 'szerokosc_twarzy',
        'parameter_name_human': 'Szerokość twarzy',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Gon.-Gon.',
        'parameter_name': 'szerokosc_zuchwy',
        'parameter_name_human': 'Szerokość żuchwy',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Ob. Głowy',
        'parameter_name': 'obwod_glowy',
        'parameter_name_human': 'Obwód głowy',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Ob. szyi',
        'parameter_name': 'obwod_szyi',
        'parameter_name_human': 'Obwód szyi',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Ob. Piersi',
        'parameter_name': 'obwod_piersi',
        'parameter_name_human': 'Obwód piersi',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Ob. w pasie',
        'parameter_name': 'obwod_w_pasie',
        'parameter_name_human': 'Obwód w pasie',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Ob. na lliosp.',
        'parameter_name': 'obwod_bioder',
        'parameter_name_human': 'Obwód bioder',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Ob. na Trochan.',
        'parameter_name': 'obwod_posladkow',
        'parameter_name_human': 'Obwód pośladków',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Najw. ob. ram.',
        'parameter_name': 'najwiekszy_obwod_ramienia',
        'parameter_name_human': 'Największy obwód ramienia',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Najw. ob. przedr.',
        'parameter_name': 'najwiekszy_obwod_przedramienia',
        'parameter_name_human': 'Największy obwód przedramienia',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Najm. ob. przedr.',
        'parameter_name': 'najmniejszy_obwod_przedramienia',

src/apps/bible/views.py
from django.views import generic

from src.apps.bible import models


class IndexView(generic.ListView):
    model = models.Bible
    template_name = 'bible/index.html'


class ShowView(generic.TemplateView):
    template_name = 'bible/show.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        bible = models.Bible.objects.get(slug=self.kwargs['slug'])
        image_id = int(self.request.GET.get('page', 1))

        context['bible'] = bible
        context['image'] = \
            models.BiblePage.objects.get(bible=bible, ordering=image_id)

        context['next_image_exists'] = \
            models.BiblePage.objects.filter(bible=bible, ordering=image_id + 1).exists()
        context['next_image_id'] = image_id + 1

        context['previous_image_exists'] = image_id > 1
        context['previous_image_id'] = image_id - 1

        context['image_id'] = image_id
        return context

src/apps/home/views.py
from django.views import generic


class HomepageView(generic.TemplateView):
    template_name = 'home/homepage.html'

src/apps/parametrizedimage/views.py
import copy
import collections
import urllib.parse

from django.views import generic

from src.apps.parametrizedimage import models


class IndexView(generic.ListView):
    template_name = 'parametrizedimage/index.html'
    paginate_by = 12

    def get_queryset(self, *args, **kwargs):
        qs = models.CardImage.objects.all()

        for parameter in models.CARD_PARAMETERS:
            if parameter['type'] == 'string':
                if parameter['parameter_name'] in self.request.GET:
                    qs = qs.filter(**{parameter['parameter_name']: self.request.GET[parameter['parameter_name']]})
            elif parameter['type'] == 'float':
                if '%s_min' % parameter['parameter_name'] in self.request.GET:
                    qs = qs.filter(**{
                        '%s__gte' % parameter['parameter_name']:
                            float(self.request.GET['%s_min' % parameter['parameter_name']])})
                if '%s_max' % parameter['parameter_name'] in self.request.GET:
                    qs = qs.filter(**{
                        '%s__lte' % parameter['parameter_name']:
                            float(self.request.GET['%s_max' % parameter['parameter_name']])})
            elif parameter['type'] == 'tags':
                # TODO
                pass
            else:
                assert(False)
        return qs

    def get_criteria(self):
        def get_url_if_removed(query_dict, parameter_name):
            new_dict = copy.copy(query_dict)
            del new_dict[parameter_name]
            url = urllib.parse.urlencode(collections.OrderedDict(new_dict))
            return '?%s' % url

        criteria = []

        for parameter in models.CARD_PARAMETERS:
            if parameter['type'] == 'string':
                if parameter['parameter_name'] in self.request.GET:
                    criteria.append({
                        'parameter_name': parameter['parameter_name'],
                        'as_text': "%s jest równe %s" % (
                            parameter['parameter_name_human'],
                            self.request.GET[parameter['parameter_name']]),
                        'url_if_removed': get_url_if_removed(
                            self.request.GET,
                            parameter['parameter_name'])
                    })
            elif parameter['type'] == 'float':
                if '%s_min' % parameter['parameter_name'] in self.request.GET:
                    criteria.append({
                        'parameter_name': parameter['parameter_name'],
                        'as_text': "%s jest większe lub równe %s" % (
                            parameter['parameter_name_human'],
                            self.request.GET['%s_min' % parameter['parameter_name']]),
                        'url_if_removed': get_url_if_removed(
                            self.request.GET,
                            '%s_min' % parameter['parameter_name'])
                    })
                if '%s_max' % parameter['parameter_name'] in self.request.GET:
                    criteria.append({
                        'parameter_name': parameter['parameter_name'],
                        'as_text': "%s jest mniejsze lub równe %s" % (
                            parameter['parameter_name_human'],
                            self.request.GET['%s_max' % parameter['parameter_name']]),
                        'url_if_removed': get_url_if_removed(
                            self.request.GET,
                            '%s_max' % parameter['parameter_name'])
                    })
            elif parameter['type'] == 'tags':
                # TODO
                pass
            else:
                assert(False)
        return criteria

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['card_parameters'] = models.CARD_PARAMETERS
        context['criteria'] = self.get_criteria()
        context['tags'] = models.CardImageTag.objects.all()
        return context


class ShowView(generic.DetailView):
    model = models.CardImage
    template_name = 'parametrizedimage/show.html'

src/apps/staticpages/views.py
from django.views import generic


class ContactView(generic.TemplateView):
    template_name = 'staticpages/contact.html'

src/templates/parametrizedimage/index.html
{% extends "base.html" %}

{% block extrahead %}
    <script src="{{ STATIC_URL }}/vendor/js/jquery-3.3.1.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.criterion-candidate select.parameter-name').bind('change', function() {
                if ($(this).find(':selected').data('type') === 'string') {
                    $('select.parameter-relation').html('');
                    $('<option name="equals">Jest równe</option>').appendTo(
                        $('select.parameter-relation'));

                    $('select.parameter-value').hide();
                    $('input.parameter-value').show();
                } else if ($(this).find(':selected').data('type') === 'float') {
                    $('select.parameter-relation').html('');
                    $('<option name="lte">Jest mniejsze lub równe</option>').appendTo(
                        $('select.parameter-relation'));
                    $('<option name="gte">Jest większe lub równe</option>').appendTo(
                        $('select.parameter-relation'));

                    $('select.parameter-value').hide();
                    $('input.parameter-value').show();
                } else if ($(this).find(':selected').data('type') === 'tags') {
                    $('select.parameter-relation').html('');
                    $('<option name="contains">Zawierają</option>').appendTo(
                        $('select.parameter-relation'));

                    $('input.parameter-value').hide();
                    $('select.parameter-value').show();
                } else {
                    console.assert(false);
                }
            });
            $('.criterion-candidate select.parameter-name').trigger('change');

            $('.criterion-candidate a.button.add').bind('click', function() {
                var relation;
                if ($('select.parameter-relation :selected').attr('name') == 'equals') {
                    relation = '';
                } else if ($('select.parameter-relation :selected').attr('name') == 'contains') {
                    relation = '';
                } else if ($('select.parameter-relation :selected').attr('name') == 'lte') {
                    relation = '_max';
                } else if ($('select.parameter-relation :selected').attr('name') == 'gte') {
                    relation = '_min';
                }

                href = window.location.href.replace(/#.*/, '')

                var separator;
                if (!href.endsWith('/')) {
                    separator = '&';
                } else {
                    separator = '?';
                }

                window.location = (
                    href +
                    separator +
                    $('.parameter-name :selected').attr('name') +
                    relation +
                    '=' +
                    encodeURIComponent($('.parameter-value').val())
                );
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="container page-card-index">
        <div class="row">
            <div class="col-xs-12">
                <h1>Karty pomiarowe</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-12 criterion-candidates" data-card-parameters="{{ card_parameters_json }}">
                <div class="criterion-candidate">
                    <select class="parameter-name">
                        {% for parameter in card_parameters %}
                            <option name="{{ parameter.parameter_name }}" data-type="{{ parameter.type }}">
                                {{ parameter.parameter_name_human }}
                            </option>
                        {% endfor %}
                    </select>
                    <select class="parameter-relation">
                    </select>
                    <input type="text" class="parameter-value" />
                    <select class="parameter-value tags">
                        {% for tag in tags %}
                            <option>{{ tag.name }}</option>
                        {% endfor %}
                    </select>

                    <a class="button add" href="#">
                        Dodaj kryterium <span class="button-icon">+</span>
                    </a>
                </div>

                <div class="criteria">
                    {% if criteria %}
                        <h2>Przyjęte kryteria</h2>
                    {% endif %}

                    {% for criterion in criteria %}
                        <div class="criterion">
                            {{ criterion.as_text }}
                            <a class="button" href="{{ criterion.url_if_removed }}">
                                Usuń kryterium <span class="button-icon">-</span>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="row">
            {% for object in object_list %}
                <div class="col-xs-12 col-sm-3">
                    <a href="{% url 'parametrizedimage:show' object.pk %}" class="card" style="background-image: url({{ MEDIA_URL }}{{ object.image }})">
                    </a>
                </div>
            {% endfor %}
        </div>

        <div class="paginator">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                {% endif %}

                <span class="current">
                    Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock %}

src/templates/parametrizedimage/show.html
{% extends "base.html" %}

{% block extrahead %}
    <script src="{{ STATIC_URL }}/vendor/js/jquery-3.3.1.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#show-more-information').bind('click', function() {
                $('.row.short-description').hide();
                $('.row.long-description').show();
            });
            $('#hide-more-information').bind('click', function() {
                $('.row.short-description').show();
                $('.row.long-description').hide();
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="container page-card-show">
        <div class="row">
            <div class="col-xs-12">
                <h1>Karta pomiarowa: {{ object.card_id }}, obraz {{ object.image_id }}</h1>
            </div>
        </div>
        <div class="row short-description">
            <div class="col-xs-12 col-sm-6">
                {% for parameter_name, parameter_value in object.get_parameter_value_dictionary_more_important %}
                    <div class="tbox">
                        <div class="tbox-left">
                            {{ parameter_name }}
                        </div>
                        <div class="tbox-right">
                            {{ parameter_value }}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-xs-12 col-sm-6">
                <div class="button-wrapper">
                    <a class="button" id="show-more-information" href="#">
                        Pokaż więcej informacji
                        <span class="button-icon">+</span>
                    </a>
                </div>
                <div class="button-wrapper">
                    <a class="button" href="{{ MEDIA_URL }}{{ object.image }}" download>
                        Pobierz plik JPG
                        <span class="button-icon">⇓</span>
                    </a>
                </div>
                <div class="button-wrapper">
                    <a class="button" href="{{ MEDIA_URL }}{{ object.pdf_file }}" download>
                        Pobierz plik PDF (wszystkie strony)
                        <span class="button-icon">⇓</span>
                    </a>
                </div>
            </div>
        </div>
        <div class="row long-description">
            <div class="col-xs-12 col-sm-6">
                {% for parameter_name, parameter_value in object.get_parameter_value_dictionary_part_1 %}
                    <div class="tbox">
                        <div class="tbox-left">
                            {{ parameter_name }}
                        </div>
                        <div class="tbox-right">
                            {{ parameter_value }}
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-xs-12 col-sm-6">
                <a class="button" id="hide-more-information" href="#">
                    Ukryj więcej informacji
                    <span class="button-icon">-</span>
                </a>
                {% for parameter_name, parameter_value in object.get_parameter_value_dictionary_part_2 %}
                    <div class="tbox">
                        <div class="tbox-left">
                            {{ parameter_name }}
                        </div>
                        <div class="tbox-right">
                            {{ parameter_value }}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="image-wrapper" style="background-image: url({{ MEDIA_URL }}{{ object.image }})">
                    {% if object.get_previous_card_image_pk %}
                        <a class="arrow-prev arrow" href="{% url 'parametrizedimage:show' object.get_previous_card_image_pk %}">
                        </a>
                    {% endif %}
                    {% if object.get_next_card_image_pk %}
                        <a class="arrow-next arrow" href="{% url 'parametrizedimage:show' object.get_next_card_image_pk %}">
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}