src/apps/bible/urls.py
from django.conf.urls import url

from src.apps.bible import views

urlpatterns = [
    url(r'^indeks/', views.IndexView.as_view(), name='index'),
    url(r'^(?P<slug>.*)', views.ShowView.as_view(), name='show'),
]

src/apps/parametrizedimage/urls.py
from django.conf.urls import url

from src.apps.parametrizedimage import views

urlpatterns = [
    url(r'^indeks/', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>.*)', views.ShowView.as_view(), name='show'),
]

src/apps/staticpages/urls.py
from django.conf.urls import url

from src.apps.staticpages import views

urlpatterns = [
    url(r'^kontakt/', views.ContactView.as_view(), name='contact'),
]

src/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.views import defaults as views_defaults

from src.apps.home.views import HomepageView


urlpatterns = [
    url(r'^$', HomepageView.as_view(), name='homepage'),
    url(r'^', include('src.apps.staticpages.urls', namespace='staticpages')),
    url(r'^biblie/', include('src.apps.bible.urls', namespace='bible')),
    url(r'^karty/', include('src.apps.parametrizedimage.urls', namespace='parametrizedimage')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # For viewing 404 and 500 pages in debug mode
    urlpatterns += [
        url(r'^404/$', views_defaults.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', views_defaults.server_error),
    ]

    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/apps/bible/models.py
from django.db import models


class Bible(models.Model):
    title = models.TextField()
    slug = models.TextField()
    cover = models.ImageField()
    pdf_file = models.FileField()


class BiblePage(models.Model):
    bible = models.ForeignKey(Bible)
    ordering = models.IntegerField()
    image_small = models.ImageField()
    image_large = models.ImageField(null=True, blank=True)

src/apps/parametrizedimage/models.py
from django.db import models


CARD_PARAMETERS = [
    {
        'csv_field_name': 'miejsce badania',
        'parameter_name': 'parameter_miejsce_badania',
        'parameter_name_human': 'Miejsce badania',
        'type': 'string',
        'more_important': True,
    },
    {
        'csv_field_name': 'data badania',
        'parameter_name': 'parameter_data_badania',
        'parameter_name_human': 'Data badania',
        'type': 'string',
        'more_important': True,
    },
    {
        'csv_field_name': 'rocznik',
        'parameter_name': 'parameter_rocznik',
        'parameter_name_human': 'Rocznik',
        'type': 'float',
        'round': True,
        'more_important': True,
    },
    {
        'csv_field_name': 'wyznanie',
        'parameter_name': 'parameter_wyznanie',
        'parameter_name_human': 'Wyznanie',
        'type': 'string',
        'more_important': True,
    },
    {
        'csv_field_name': 'jezyk',
        'parameter_name': 'parameter_jezyk',
        'parameter_name_human': 'Język',
        'type': 'string',
        'more_important': True,
    },
    {
        'csv_field_name': 'powiat urodzenia',
        'parameter_name': 'parameter_powiat_urodzenia',
        'parameter_name_human': 'Powiat urodzenia',
        'type': 'string',
        'more_important': True,
    },
    {
        'csv_field_name': 'waga',
        'parameter_name': 'parameter_waga',
        'parameter_name_human': 'Waga',
        'type': 'float',
        'more_important': True,
    },
    {
        'csv_field_name': 'wzrost',
        'parameter_name': 'parameter_wzrost',
        'parameter_name_human': 'Wzrost',
        'type': 'float',
        'more_important': True,
    },
    {
        'csv_field_name': 'gnathion',
        'parameter_name': 'parameter_wzrost_od_ziemi_do_podbrodka',
        'parameter_name_human': 'Wzrost od ziemi do podbródka',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'suprasternale',
        'parameter_name': 'parameter_wzrost_od_ziemi_do_mostka',
        'parameter_name_human': 'Wzrost od ziemi do mostka',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'symphysion',
        'parameter_name': 'parameter_wzrost_do_wzgorka_lonowego',
        'parameter_name_human': 'Wzrost od ziemi do wzgórka łonowego',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'tibiale',
        'parameter_name': 'parameter_wzrost_do_kolan',
        'parameter_name_human': 'Wzrost do kolan',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'sphyrion',
        'parameter_name': 'parameter_wzrost_do_kostki',
        'parameter_name_human': 'Wzrost do kostki',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'akromion',
        'parameter_name': 'parameter_wzrost_od_ziemi_do_ramienia',
        'parameter_name_human': 'Wzrost od ziemi do ramienia',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'radiale',
        'parameter_name': 'parameter_od_ziemi_do_lokcia',
        'parameter_name_human': 'Wzrost od ziemi do łokcia',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'stylion',
        'parameter_name': 'parameter_od_ziemi_do_nadgarstka',
        'parameter_name_human': 'Wzrost od ziemi do nadgarstka',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'daktylion',
        'parameter_name': 'parameter_od_ziemi_do_konca_palca_srodkowego',
        'parameter_name_human': 'Wzrost od ziemi do końca palca środkowego',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'pterion-akrop(odion).',
        'parameter_name': 'parameter_dlugosc_stopy_od_piety_do_duzego_palca_u_nogi',
        'parameter_name_human': 'Długość stopy od pięty do dużego palca u nogi',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Mtr. I,-mtr. m.',
        'parameter_name': 'parameter_szerokosc_stopy',
        'parameter_name_human': 'Szerokość stopy',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Akrom-Akrom',
        'parameter_name': 'parameter_szerokosc_w_barkach',
        'parameter_name_human': 'Szerokość w barkach',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Śr. piers. poprz.',
        'parameter_name': 'parameter_szerokosc_klatki_piersiowej',
        'parameter_name_human': 'Szerokość klatki piersiowej',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Śr. piers. strz.',
        'parameter_name': 'parameter_glebokosc_klatki_piersiowej',
        'parameter_name_human': 'Głębokość klatki piersiowej',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Iliocrist.-illiocr.',
        'parameter_name': 'parameter_szerokosc_w_biodrach',
        'parameter_name_human': 'Szerokość w biodrach',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Metacar. l.-met. m.',
        'parameter_name': 'parameter_szerokosc_dloni',
        'parameter_name_human': 'Szerokość dłoni',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Phal(angion)III-Dakt.',
        'parameter_name': 'parametr_dlugosc_palca_srodkowego',
        'parameter_name_human': 'Długość palca środkowego',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Nasion.-Gnath.',
        'parameter_name': 'parametr_wysokosc_twarzy_od_brody_do_poziomu_oczu',
        'parameter_name_human': 'Wysokość twarzy od brody do poziomu oczu',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Nas.-Prosth.',
        'parameter_name': 'parameter_od_oczu_do_gornej_szczeki',
        'parameter_name_human': 'Odległość od oczu do górnej szczęki',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Nas.-Subnas.',
        'parameter_name': 'parameter_wysokosc_nosa',
        'parameter_name_human': 'Wysokość nosa',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Alare.-Alare.',
        'parameter_name': 'parameter_szerokosc_nosa_u_podstawy',
        'parameter_name_human': 'Szerokość nosa u podstawy',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Glab.-Opist.',
        'parameter_name': 'parameter_dlugosc_czaszki_od_czola_do_potylicy',
        'parameter_name_human': 'Długość czaszki od czoła do potylicy',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Eur.-Eur.',
        'parameter_name': 'parameter_szerokosc_czaszki_na_wysokosci_oczu',
        'parameter_name_human': 'Szerokość czaszki na wysokości oczu',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Mast.-Mast.',
        'parameter_name': 'parameter_szerokosc_czaszki_na_wysokosci_uszu',
        'parameter_name_human': 'Szerokość czaszki na wysokości uszu',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Front.-Front.',
        'parameter_name': 'szerokosc_czola',
        'parameter_name_human': 'Szerokość czoła',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Zyg.-Zyg.',
        'parameter_name': 'szerokosc_twarzy',
        'parameter_name_human': 'Szerokość twarzy',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Gon.-Gon.',
        'parameter_name': 'szerokosc_zuchwy',
        'parameter_name_human': 'Szerokość żuchwy',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Ob. Głowy',
        'parameter_name': 'obwod_glowy',
        'parameter_name_human': 'Obwód głowy',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Ob. szyi',
        'parameter_name': 'obwod_szyi',
        'parameter_name_human': 'Obwód szyi',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Ob. Piersi',
        'parameter_name': 'obwod_piersi',
        'parameter_name_human': 'Obwód piersi',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Ob. w pasie',
        'parameter_name': 'obwod_w_pasie',
        'parameter_name_human': 'Obwód w pasie',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Ob. na lliosp.',
        'parameter_name': 'obwod_bioder',
        'parameter_name_human': 'Obwód bioder',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Ob. na Trochan.',
        'parameter_name': 'obwod_posladkow',
        'parameter_name_human': 'Obwód pośladków',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Najw. ob. ram.',
        'parameter_name': 'najwiekszy_obwod_ramienia',
        'parameter_name_human': 'Największy obwód ramienia',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Najw. ob. przedr.',
        'parameter_name': 'najwiekszy_obwod_przedramienia',
        'parameter_name_human': 'Największy obwód przedramienia',
        'type': 'float',
        'more_important': False,
    },
    {
        'csv_field_name': 'Najm. ob. przedr.',
        'parameter_name': 'najmniejszy_obwod_przedramienia',

src/apps/bible/views.py
from django.views import generic

from src.apps.bible import models


class IndexView(generic.ListView):
    model = models.Bible
    template_name = 'bible/index.html'


class ShowView(generic.TemplateView):
    template_name = 'bible/show.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        bible = models.Bible.objects.get(slug=self.kwargs['slug'])
        image_id = int(self.request.GET.get('page', 1))

        context['bible'] = bible
        context['image'] = \
            models.BiblePage.objects.get(bible=bible, ordering=image_id)

        context['next_image_exists'] = \
            models.BiblePage.objects.filter(bible=bible, ordering=image_id + 1).exists()
        context['next_image_id'] = image_id + 1

        context['previous_image_exists'] = image_id > 1
        context['previous_image_id'] = image_id - 1

        context['image_id'] = image_id
        return context

src/apps/home/views.py
from django.views import generic


class HomepageView(generic.TemplateView):
    template_name = 'home/homepage.html'

src/apps/parametrizedimage/views.py
import copy
import collections
import urllib.parse

from django.views import generic

from src.apps.parametrizedimage import models


class IndexView(generic.ListView):
    template_name = 'parametrizedimage/index.html'
    paginate_by = 12

    def get_queryset(self, *args, **kwargs):
        qs = models.CardImage.objects.all()

        for parameter in models.CARD_PARAMETERS:
            if parameter['type'] == 'string':
                if parameter['parameter_name'] in self.request.GET:
                    qs = qs.filter(**{parameter['parameter_name']: self.request.GET[parameter['parameter_name']]})
            elif parameter['type'] == 'float':
                if '%s_min' % parameter['parameter_name'] in self.request.GET:
                    qs = qs.filter(**{
                        '%s__gte' % parameter['parameter_name']:
                            float(self.request.GET['%s_min' % parameter['parameter_name']])})
                if '%s_max' % parameter['parameter_name'] in self.request.GET:
                    qs = qs.filter(**{
                        '%s__lte' % parameter['parameter_name']:
                            float(self.request.GET['%s_max' % parameter['parameter_name']])})
            elif parameter['type'] == 'tags':
                # TODO
                pass
            else:
                assert(False)
        return qs

    def get_criteria(self):
        def get_url_if_removed(query_dict, parameter_name):
            new_dict = copy.copy(query_dict)
            del new_dict[parameter_name]
            url = urllib.parse.urlencode(collections.OrderedDict(new_dict))
            return '?%s' % url

        criteria = []

        for parameter in models.CARD_PARAMETERS:
            if parameter['type'] == 'string':
                if parameter['parameter_name'] in self.request.GET:
                    criteria.append({
                        'parameter_name': parameter['parameter_name'],
                        'as_text': "%s jest równe %s" % (
                            parameter['parameter_name_human'],
                            self.request.GET[parameter['parameter_name']]),
                        'url_if_removed': get_url_if_removed(
                            self.request.GET,
                            parameter['parameter_name'])
                    })
            elif parameter['type'] == 'float':
                if '%s_min' % parameter['parameter_name'] in self.request.GET:
                    criteria.append({
                        'parameter_name': parameter['parameter_name'],
                        'as_text': "%s jest większe lub równe %s" % (
                            parameter['parameter_name_human'],
                            self.request.GET['%s_min' % parameter['parameter_name']]),
                        'url_if_removed': get_url_if_removed(
                            self.request.GET,
                            '%s_min' % parameter['parameter_name'])
                    })
                if '%s_max' % parameter['parameter_name'] in self.request.GET:
                    criteria.append({
                        'parameter_name': parameter['parameter_name'],
                        'as_text': "%s jest mniejsze lub równe %s" % (
                            parameter['parameter_name_human'],
                            self.request.GET['%s_max' % parameter['parameter_name']]),
                        'url_if_removed': get_url_if_removed(
                            self.request.GET,
                            '%s_max' % parameter['parameter_name'])
                    })
            elif parameter['type'] == 'tags':
                # TODO
                pass
            else:
                assert(False)
        return criteria

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['card_parameters'] = models.CARD_PARAMETERS
        context['criteria'] = self.get_criteria()
        context['tags'] = models.CardImageTag.objects.all()
        return context


class ShowView(generic.DetailView):
    model = models.CardImage
    template_name = 'parametrizedimage/show.html'

src/apps/staticpages/views.py
from django.views import generic


class ContactView(generic.TemplateView):
    template_name = 'staticpages/contact.html'

src/templates/base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="pl">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="{% block meta_description %}{% endblock %}"/>
  <title>{% block title %}Repostorium Muzeum Historii Polski{% endblock title %}</title>
  {% if GOOGLE_ANALYTICS_ID %}
    <!-- Google Analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', '{ GOOGLE_ANALYTICS_ID }', 'auto');
      ga('send', 'pageview');
    </script>
    <!-- End Google Analytics -->
  {% endif %}

  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500&amp;subset=latin-ext" rel="stylesheet">

  {% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static 'scss/main.scss' %}" />
  {% endcompress %}

  {% compress js %}
    <script type="module" src="{% static 'js/main.js' %}"></script>
  {% endcompress %}

  {% block extrahead %}
  {% endblock extrahead %}
</head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Pokaż/ukryj nawigację</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'homepage' %}"><img src="{{ STATIC_URL }}/img/logo-repostorium.svg" /></a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'parametrizedimage:index' %}">karty pomiarowe</a></li>
              <li><a href="{% url 'bible:index' %}">biblie</a></li>
              <li><a href="{% url 'staticpages:contact' %}">kontakt</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <footer class="footer">
        <div class="container">
            <div class="row tbox">
                <div class="col-xs-12 col-sm-4 tbox-left legal-disclaimer-box">
                    O ile nie zaznaczono inaczej, wszystkie dokumenty prezentowane w serwisie
                    są w Domenie Publicznej (nie podlegają ochronie prawnoautorskiej).
                    <br/>
                    <br/>
                    Pozostałe elementy w serwisie są dostępne na licencji
                    <a href="https://creativecommons.org/licenses/by-sa/3.0/deed.pl">
                        Creative Commons Uznanie autorstwa - na tych samych warunkach 3.0
                    </a>
                </div>
                <div class="col-xs-12 col-sm-8 tbox-right logo-box">
                    <div class="logo-box-item">
                        <img class="height-2" src="{{ STATIC_URL }}/img/logo-mhp.png" />
                    </div>
                    <div class="logo-box-item">
                        <div class="hint">
                        stworzone w:
                        </div>
                        <img class="height-2" src="{{ STATIC_URL }}/img/logo-pok.png" />
                    </div>
                    <div class="logo-box-item">
                        <img class="height-1" src="{{ STATIC_URL }}/img/logo-mkidn.svg" />
                    </div>
                    <div class="logo-box-item">
                        <img class="height-1" src="{{ STATIC_URL }}/img/logo-cc.png" />
                    </div>
                    <div class="text">
                        Dofinansowano ze środków Ministra Kultury i Dziedzictwa Narodowego.
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 authors">
                    projekt strony: <a href="http://www.syfonstudio.com/">syfonstudio</a>
                </div>
            </div>
        </div>
    </footer>
</body>

</html>